name: 'Publish Prebuilt Module'
description: 'Publish Prebuilt Module'
inputs:
  repository:
    description: 'Target repository to download the release from'
    required: true
  release_token:
    description: 'Token required to publish a release'
    required: true
  access_token:
    description: 'Token required to download the release'
    required: true
    default: ''
  release_tag:
    description: 'Tag to use for the release'
    required: true
runs:
  using: "composite"
  steps: 
    - uses: robinraju/release-downloader@v1.6
      with: 
        repository: "${{ inputs.repository }}"
        tag: "latest"
        fileName: "binaries_linux64.tar.gz"
        out-file-path: "."
        token: "${{ inputs.access_token }}"

    - uses: robinraju/release-downloader@v1.6
      with: 
        repository: "${{ inputs.repository }}"
        tag: "latest"
        fileName: "binaries_windows64.zip"
        out-file-path: "."
        token: "${{ inputs.access_token }}"
        
    - name: Update Nightly Tag
      uses: rickstaa/action-create-tag@v1.3.9
      continue-on-error: true
      with:
        tag: "${{ inputs.release_tag }}"
        force_push_tag: true

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "binaries_linux64.tar.gz,binaries_windows64.zip"
        body: "Automatically generated binaries."
        commit: ${{ github.ref_name }}
        token: "${{ inputs.release_token }}"
        tag: "${{ inputs.release_tag }}"
        replacesArtifacts: true
        allowUpdates: true
