name: 'Initialize Env'
description: 'Initialize common env variables'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action Start: set_common_env_vars ===\n"

    - name: Init Env
      shell: bash
      run: |
        echo "GA_ROOT_DIR=$PWD" >> $GITHUB_ENV
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "GA_STATIC_LINK_LIBRARY_EXT=.a" >> $GITHUB_ENV
          echo "GA_SHARED_LINK_LIBRARY_EXT=.so" >> $GITHUB_ENV
          echo "GA_SHARED_BINARY_LIBRARY_EXT=.so" >> $GITHUB_ENV
          echo "GA_STATIC_LIBRARY_PREFIX=lib" >> $GITHUB_ENV
        else
          echo "GA_STATIC_LINK_LIBRARY_EXT=.lib" >> $GITHUB_ENV
          echo "GA_SHARED_LINK_LIBRARY_EXT=.lib" >> $GITHUB_ENV
          echo "GA_SHARED_BINARY_LIBRARY_EXT=.dll" >> $GITHUB_ENV
          echo "GA_STATIC_LIBRARY_PREFIX=" >> $GITHUB_ENV
        fi

        ga_print()
        {
          printf "\033[0;31m$1\033[0m\n"
        }
        export -f ga_print
        
        if [ ! -d "./build" ]; then
          mkdir build
        fi
        
    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action End: set_common_env_vars ==="
