name: 'Initialize Env'
description: 'Initialize common env variables'
runs:
  using: "composite"
  steps: 
    - name: Build
      shell: bash
      run: |
        GA_ROOT_DIR=$PWD
        if [ "$RUNNER_OS" == "Linux" ]; then
          GA_STATIC_LINK_LIBRARY_EXT=.a
          GA_SHARED_LINK_LIBRARY_EXT=.so
          GA_SHARED_BINARY_LIBRARY_EXT=.so
        else
          GA_STATIC_LINK_LIBRARY_EXT=.lib
          GA_SHARED_LINK_LIBRARY_EXT=.lib
          GA_SHARED_BINARY_LIBRARY_EXT=.dll
        fi
        
