name: 'Initialize Env'
description: 'Initialize common env variables'
runs:
  using: "composite"
  steps: 
    - name: Build
      shell: bash
      run: |
        GA_TEST_VALUE="HelloWorld"
        export GA_TEST_VALUE2="ByeWorld"
        export GA_ROOT_DIR=$PWD
        if [ "$RUNNER_OS" == "Linux" ]; then
          export GA_STATIC_LINK_LIBRARY_EXT=".a"
          export GA_SHARED_LINK_LIBRARY_EXT=".so"
          export GA_SHARED_BINARY_LIBRARY_EXT=".so"
        else
          export GA_STATIC_LINK_LIBRARY_EXT=".lib"
          export GA_SHARED_LINK_LIBRARY_EXT=".lib"
          export GA_SHARED_BINARY_LIBRARY_EXT=".dll"
        fi
      env:
        TEST_ENV_VAR: FelisCatus
outputs:
  random-number:
    description: "Random number"
    value: 12734
  env-string:
    description: "Random numberX"
    value: "export VAR1=value1 VAR2=555 VARN=$GA_TEST_VALUE VARN2=$GA_TEST_VALUE2"
