name: 'Initialize Env'
description: 'Initialize common env variables'
runs:
  using: "composite"
  steps: 
    - name: Init Env
      shell: bash
      run: |
        echo "GA_ROOT_DIR=$PWD" >> $GITHUB_ENV
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "GA_STATIC_LINK_LIBRARY_EXT=.a" >> $GITHUB_ENV
          echo "GA_SHARED_LINK_LIBRARY_EXT=.so" >> $GITHUB_ENV
          echo "GA_SHARED_BINARY_LIBRARY_EXT=.so" >> $GITHUB_ENV
          echo "GA_STATIC_LIBRARY_PREFIX=lib" >> $GITHUB_ENV
        else
          echo "GA_STATIC_LINK_LIBRARY_EXT=.lib" >> $GITHUB_ENV
          echo "GA_SHARED_LINK_LIBRARY_EXT=.lib" >> $GITHUB_ENV
          echo "GA_SHARED_BINARY_LIBRARY_EXT=.dll" >> $GITHUB_ENV
          echo "GA_STATIC_LIBRARY_PREFIX=" >> $GITHUB_ENV
        fi
        
        if [ ! -d "./build" ]; then
          mkdir build
        fi
        
