name: 'Get Submodule'
description: 'Downloads and builds a git submodule'
inputs:
  repo:
    description: 'Repository Url'
    required: true
  repo_name:
    description: 'Name of the repository'
    required: true
  repo_branch:
    description: 'Branch to clone'
    required: true
    default: 'master'
  dir:
    description: 'Clone directory'
    required: true
    default: 'external_libs'
  should_build:
    description: 'Should build?'
    required: true
    default: true
  build_type:
    description: 'Build Type'
    required: true
  build_generator:
    description: 'Build Generator'
    required: true
  include_dir:
    description: 'Name of the include directory'
    required: true
    default: 'include'
  cmake_definitions:
    description: 'CMake definitions'
    required: true
    default: ''
  cmake_var:
    description: 'Name of the CMake variable to set to the include path'
    required: true
    default: ''
  cmake_var_alias:
    description: 'Alias CMake variable name'
    required: true
    default: ''
  root_dir:
    description: 'Root directory'
    required: true
    default: ''
  checkout_submodules:
    description: 'Checkout submodules?'
    required: true
    default: '1'
outputs:
  cmake_definitions:
    description: "CMake definitions output"
    value: ${{ steps.clone.outputs.cmake_definitions }}
  include_directory:
    description: 'The include directory for this library'
    value: ${{ steps.clone.outputs.include-directory }}
runs:
  using: "composite"
  steps: 
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      
    - name: Clone
      shell: bash
      id: clone
      run: |
        if [[ "${{ inputs.root_dir }}" != "" ]]; then
          root_dir=${{ inputs.root_dir }}
        else
          root_dir=${{ env.GA_ROOT_DIR }}
        fi
        cd $root_dir
        
        # Only get submodule if directly doesn't exist or is empty
        if [[ ! -d "${{ inputs.dir }}/${{ inputs.repo_name }}" || -z "$(ls -A ${{ inputs.dir }}/${{ inputs.repo_name }})" ]]; then
          mkdir -p ${{ inputs.dir }}
          cd ${{ inputs.dir }}
          
          repo=${{ inputs.repo }}
          # Add "https://github.com/" prefix if repo doesn't start with "http"
          case $repo in http*) :; ;; (*) repo='https://github.com/'$repo; ;; esac
          
          echo "Git clone..."
          git clone $repo --single-branch --branch ${{ inputs.repo_branch }} ${{ inputs.repo_name }}
          echo "Done!"
          
          cd ${{ inputs.repo_name }}
          echo "Git checkout..."
          git checkout ${{ inputs.repo_branch }}
          echo "Done!"
          
          if [[ "${{ inputs.checkout_submodules }}" == "1" ]]; then
            echo "Git submodule..."
            git submodule update --init --recursive
            echo "Done!"
          fi
          
          commitId=$(git rev-parse --short=10 HEAD);
          # TODO: Save commit id with binary cache?
        fi
        
        echo "Updating outputs and definitions..."
        fullIncludePath="${{ env.GA_ROOT_DIR }}/${{ inputs.dir }}/${{ inputs.repo_name }}/${{ inputs.include_dir }}"
        nfullIncludePath="${fullIncludePath//.\//}"
        echo "::set-output name=include-directory::$nfullIncludePath"
        if [[ "${{ inputs.cmake_var }}" != "" ]]; then
          newCmakeDef=" -D${{ inputs.cmake_var }}=$fullIncludePath"
          if [[ "${{ inputs.cmake_var_alias }}" != "" ]]; then
            newCmakeDef="$newCmakeDef -D${{ inputs.cmake_var_alias }}=$fullIncludePath"
          fi
        else
          newCmakeDef=""
        fi
        echo ::set-output name=cmakeDefLocal::$(echo $newCmakeDef)
        echo "Done!"

    - name: Define CMake Variable
      uses: Silverlan/common_actions/define_cmake_var@main
      with:
        cmake_var: '${{ steps.clone.outputs.cmakeDefLocal }}'
        
