name: 'Action Start'
description: 'Action Start'
inputs:
  name:
    description: 'Message'
    required: true
  input_values:
    description: 'Input Values'
    required: true
    default: ''
runs:
  using: "composite"
  steps: 
    - name: Print
      shell: bash
      run: |
        # Add step to env variables
        newTest="${{ env.GA_SUB_STEP }}""#${{inputs.name}}""?${{inputs.input_values}}"
        echo "GA_SUB_STEP=$(echo $newTest)" >> $GITHUB_ENV
      
        # Print
        IFS='#' read -ra ADDR <<< "${{ env.GA_SUB_STEP }}"
        str=""
        first='2'
        curAction=''
        args=''
        for i in "${ADDR[@]}"; do
          IFS='?' read -ra CMP <<< "$i"
          if [ $first -eq '2' ] 
          then
            first='1'
          else
            if [ $first -eq '1' ] 
            then
              first='0'
            else
              str="$str > "
            fi
            str="$str${CMP[0]}"
          fi
        done
        
        output="Action Start: $str > ${{inputs.name}}"
        printf "\033[0;32m=== $output ===\n"
        
        printf "\033[0;32mInput Values:\n"
        IFS=',' read -ra ADDR <<< "${{inputs.input_values}}"
        for i in "${ADDR[@]}"; do
          printf "\033[1;32m$i\n"
        done
        
