name: 'Generic CMake build'
description: 'Builds the specified project'
inputs:
  cmake_definitions:
    description: 'CMake definitions'
    required: true
    default: ''
  build_type:
    description: 'Build Type'
    required: true
  build_generator:
    description: 'Build Generator'
    required: true
  build_target:
    description: 'Main target to build'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Build
      shell: bash
      env:
        CC:   gcc-11
        CXX:  g++-11
      run: |
        mkdir -p build
        cd build
        cmake ../ ${{ inputs.cmake_definitions }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -G "${{ inputs.build_generator }}"
        cmake --build ./ --config ${{ matrix.config.build_type }} --target ${{ matrix.config.build_target }}
