name: 'Generic CMake build'
description: 'Builds the specified project'
inputs:
  cmake_definitions:
    description: 'CMake definitions'
    required: true
    default: ''
  build_type:
    description: 'Build Type'
    required: true
  build_generator:
    description: 'Build Generator'
    required: true
  build_target:
    description: 'Main target to build'
    required: true
  build_dir:
    description: 'The directory to write the build files to'
    required: true
    default: 'build'
  cmake_script_location:
    description: 'The location of the CMake script'
    required: true
    default: '.'
runs:
  using: "composite"
  steps: 
    - name: Build
      shell: bash
      env:
        CC:   gcc-11
        CXX:  g++-11
      run: |
        GA_ROOT_DIR=$PWD
        mkdir -p ${{ inputs.build_dir }}
        cd ${{ inputs.build_dir }}
        cmake ../ ${{ inputs.cmake_definitions }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -G "${{ inputs.build_generator }}"
        cmake --build $GA_ROOT_DIR/${{ inputs.cmake_script_location }} --config ${{ matrix.config.build_type }} --target ${{ inputs.build_target }}
