name: 'Get common external Pragma libraries'
description: 'Downloads and builds the common external Pragma libraries.'
runs:
  using: "composite"
  steps: 
    - name: Download submodule - GLM
      uses: Silverlan/common_actions/get_glm@main

    - name: Build submodule - mathutil
      uses: Silverlan/common_actions/build_submodule@main
      with:
        repo: 'https://github.com/Silverlan/mathutil.git'
        repo_name: 'mathutil'
        build_target: 'mathutil'
        root_dir: 'external_libs'

    - name: Build submodule - sharedutils
      uses: Silverlan/common_actions/build_submodule@main
      with:
        repo: 'https://github.com/Silverlan/sharedutils.git'
        repo_name: 'sharedutils'
        build_target: 'sharedutils'
        root_dir: 'external_libs'

    - name: Build submodule - vfilesystem
      uses: Silverlan/common_actions/build_submodule@main
      with:
        repo: 'https://github.com/Silverlan/vfilesystem.git'
        repo_name: 'vfilesystem'
        build_target: 'vfilesystem'
        root_dir: 'external_libs'
