name: 'Get common external Pragma libraries'
description: 'Downloads and builds the common external Pragma libraries.'
inputs:
  build_shared:
    description: 'Build as shared library?'
    required: true
    default: '1'
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
runs:
  using: "composite"
  steps: 
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      with:
        working-directory: ${{inputs.working-directory}}
      
    - name: Download GLM
      uses: Silverlan/common_actions/get_glm@main
      with:
        cmake_var: 'DEPENDENCY_GLM_INCLUDE'
        cmake_definitions: ${{ env.cmake_definitions }}
        working-directory: ${{inputs.working-directory}}
        
    - name: Build GeometricTools
      uses: Silverlan/common_actions/build_geometric_tools@main
      with:
        working-directory: ${{inputs.working-directory}}
      
    - name: Initialize CMake definitions
      id: init-cmake-defs
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        tmpCmakeVars=''
        buildAsStatic='0'
        if [[ "${{ inputs.build_shared }}" == "0" ]]; then
          tmpCmakeVars=' -DMATHUTIL_STATIC=ON -DSHAREDUTILS_STATIC=ON -DVFILESYSTEM_STATIC=ON -DLINK_COMMON_LIBS_STATIC=ON'
          buildAsStatic='1'
        fi
        echo "::set-output name=tmp-cmake-vars::$(echo $tmpCmakeVars)"
        echo "::set-output name=build-as-static::$(echo $buildAsStatic)"

    - name: Download mathutil
      uses: Silverlan/common_actions/get_submodule@main
      with:
        repo: 'https://github.com/Silverlan/mathutil.git'
        repo_name: 'mathutil'
        dir: 'external_libs'
        cmake_var: 'DEPENDENCY_MATHUTIL_INCLUDE'
        working-directory: ${{inputs.working-directory}}

    - name: Install libltdl 
      shell: bash
      if: runner.os == 'Linux'
      working-directory: ${{inputs.working-directory}}
      run: |
        sudo apt-get install help2man

    - name: Download sharedutils
      uses: Silverlan/common_actions/get_submodule@main
      with:
        repo: 'https://github.com/Silverlan/sharedutils.git'
        repo_name: 'sharedutils'
        dir: 'external_libs'
        cmake_var: 'DEPENDENCY_SHAREDUTILS_INCLUDE'
        working-directory: ${{inputs.working-directory}}
        
    # Build
    - name: Build sharedutils-static
      uses: Silverlan/common_actions/build_cmake@main
      with:
        build_type: ${{ matrix.config.build_type }}
        build_generator: ${{ matrix.config.generators }}
        cmake_definitions_tmp: "${{ steps.init-cmake-defs.outputs.tmp-cmake-vars }} ${{ env.cmake_definitions }} -DSHAREDUTILS_STATIC=ON -DDEPENDENCY_MATHUTIL_INCLUDE=$GA_ROOT_DIR/external_libs/mathutil/include"
        build_target: 'sharedutils'
        build_dir: 'build/external_libs/sharedutils-static'
        cmake_script_location: 'external_libs/sharedutils'
        cmake_var: 'DEPENDENCY_SHAREDUTILS_LIBRARY_STATIC'
        cmake_definitions: ${{ env.cmake_definitions }}
        static_library: '1'
        working-directory: ${{inputs.working-directory}}
        
    - name: Build mathutil
      uses: Silverlan/common_actions/build_cmake@main
      with:
        build_type: ${{ matrix.config.build_type }}
        build_generator: ${{ matrix.config.generators }}
        build_target: 'mathutil'
        build_dir: 'build/external_libs/mathutil'
        cmake_script_location: 'external_libs/mathutil'
        cmake_var: 'DEPENDENCY_MATHUTIL_LIBRARY'
        cmake_definitions_tmp: "${{ steps.init-cmake-defs.outputs.tmp-cmake-vars }}"
        static_library: '${{ steps.init-cmake-defs.outputs.build-as-static }}'
        working-directory: ${{inputs.working-directory}}
        
    - name: Build sharedutils
      uses: Silverlan/common_actions/build_cmake@main
      with:
        build_type: ${{ matrix.config.build_type }}
        build_generator: ${{ matrix.config.generators }}
        build_target: 'sharedutils'
        build_dir: 'build/external_libs/sharedutils'
        cmake_script_location: 'external_libs/sharedutils'
        cmake_var: 'DEPENDENCY_SHAREDUTILS_LIBRARY'
        cmake_definitions_tmp: "${{ steps.init-cmake-defs.outputs.tmp-cmake-vars }}"
        static_library: '${{ steps.init-cmake-defs.outputs.build-as-static }}'
        working-directory: ${{inputs.working-directory}}

    - name: Download bzip2
      uses: Silverlan/common_actions/get_submodule@main
      with:
        dir: 'third_party_libs'
        repo: 'https://github.com/sergiud/bzip2.git'
        repo_name: 'bzip2'
        repo_branch: 'cmake'
        cmake_var: 'DEPENDENCY_BZIP2_INCLUDE'
        cmake_definitions: ${{ env.cmake_definitions }}
        include_dir: '.'
        working-directory: ${{inputs.working-directory}}

    - name: Build vfilesystem
      uses: Silverlan/common_actions/build_submodule@main
      with:
        repo: 'https://github.com/Silverlan/vfilesystem.git'
        repo_name: 'vfilesystem'
        build_target: 'vfilesystem'
        top_level_dir: 'external_libs'
        cmake_definitions_tmp: "${{ steps.init-cmake-defs.outputs.tmp-cmake-vars }}"
        static_library: '${{ steps.init-cmake-defs.outputs.build-as-static }}'
        cmake_var: 'DEPENDENCY_VFILESYSTEM_INCLUDE'
        cmake_var_lib: 'DEPENDENCY_VFILESYSTEM_LIBRARY'
        working-directory: ${{inputs.working-directory}}
