name: 'Get common external Pragma libraries'
description: 'Downloads and builds the common external Pragma libraries.'
runs:
  using: "composite"
  steps: 
    - name: Download submodule - GLM
      uses: Silverlan/common_actions/get_glm@main

    - name: Download submodule - mathutil
      uses: Silverlan/common_actions/get_submodule@main
      with:
        repo: 'https://github.com/Silverlan/mathutil.git'
        repo_name: 'mathutil'

    - name: Download submodule - sharedutils
      uses: Silverlan/common_actions/get_submodule@main
      with:
        repo: 'https://github.com/Silverlan/sharedutils.git'
        repo_name: 'sharedutils'

    - name: Download submodule - vfilesystem
      uses: Silverlan/common_actions/get_submodule@main
      with:
        repo: 'https://github.com/Silverlan/vfilesystem.git'
        repo_name: 'vfilesystem'
