name: 'Get GLI'
description: 'Downloads the GLI library'
inputs:
  cmake_definitions:
    description: 'CMake definitions'
    required: true
    default: 'external_libs'
  cmake_var:
    description: 'Name of the CMake variable to set to the include path'
    required: true
    default: ''
runs:
  using: "composite"
  steps: 
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@actions
      
    - name: Get submodule - GLI
      uses: Silverlan/common_actions/get_submodule@actions
      with:
        repo: 'https://github.com/g-truc/gli.git'
        repo_name: 'gli'
        cmake_var: 'DEPENDENCY_GLI_INCLUDE'
        dir: 'third_party_libs'
        
    - shell: bash
      id: set-cmake-var
      run: |
        newCmakeDef=" -D${{ inputs.cmake_var }}=${{ env.GA_ROOT_DIR }}/third_party_libs/gli"
        echo ::set-output name=cmakeDefLocal::$(echo $newCmakeDef)

    - name: Define CMake Variable
      uses: Silverlan/common_actions/define_cmake_var@actions
      with:
        cmake_var: '${{ steps.set-cmake-var.outputs.cmakeDefLocal }}'
        
