name: 'Get GLI'
description: 'Downloads the GLI library'
inputs:
  cmake_definitions:
    description: 'CMake definitions'
    required: true
    default: 'external_libs'
  cmake_var:
    description: 'Name of the CMake variable to set to the include path'
    required: true
    default: ''
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "get_gli"
        input_values: "cmake_definitions: ${{inputs.cmake_definitions}},cmake_var: ${{inputs.cmake_var}},working-directory: ${{inputs.working-directory}}"

    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      with:
        working-directory: ${{inputs.working-directory}}
      
    - name: Get submodule - GLI
      uses: Silverlan/common_actions/get_submodule@main
      with:
        repo: 'https://github.com/g-truc/gli.git'
        repo_name: 'gli'
        cmake_var: 'DEPENDENCY_GLI_INCLUDE'
        dir: 'third_party_libs'
        working-directory: ${{inputs.working-directory}}
        
    - shell: bash
      id: set-cmake-var
      working-directory: ${{inputs.working-directory}}
      run: |
        newCmakeDef=" -D${{ inputs.cmake_var }}=$PWD/third_party_libs/gli"
        echo ::set-output name=cmakeDefLocal::$(echo $newCmakeDef)

    - name: Define CMake Variable
      uses: Silverlan/common_actions/define_cmake_var@main
      with:
        cmake_var: '${{ steps.set-cmake-var.outputs.cmakeDefLocal }}'
        
    - uses: Silverlan/common_actions/action_end@main
