name: 'Setup Pragma Module'
description: 'Setup Pragma Module'
inputs:
  cc_version:
    description: 'CC Version'
    required: true
    default: 'gcc-12'
  cxx_version:
    description: 'CXX Version'
    required: true
    default: 'g++-12'
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
outputs:
  cmake_defs:
    description: "CMake Definitions"
    value: ${{ steps.defs.outputs.cmake_definitions }}
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "setup_pragma_module"
        input_values: "cc_version: ${{inputs.cc_version}},cxx_version: ${{inputs.cxx_version}},working-directory: ${{inputs.working-directory}}"

    - name: Download dependencies
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        git clone --recursive https://github.com/Silverlan/pragma.git pragma
  
    - name: Get Pragma CMake Definitions
      id: pragma-cmake-defs
      uses: Silverlan/common_actions/get_pragma_cmake_defs@main
      with:
        pragma_location: './pragma'
        
    - name: Setup
      id: setup
      uses: Silverlan/common_actions/setup@main
      with:
        cc_version: ${{ inputs.cc_version }}
        cxx_version: ${{ inputs.cc_version }}
        
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      
    - name: Output Definitions
      id: defs
      shell: bash
      run: echo "cmake_definitions=${{ steps.pragma-cmake-defs.outputs.cmake_defs }}" >> $GITHUB_OUTPUT
      
    - uses: Silverlan/common_actions/action_end@main
