name: 'Print Message'
description: 'Print Message'
inputs:
  message:
    description: 'Message'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Print
      shell: bash
      run: |
        string="${{ inputs.message }}"
        src='\\n'
        dst='\\n\\033[0;31m'
        
        newMsg=$(echo "$string" | sed "s/$src/$dst/g")
        printf "\033[0;31m$newMsg"
        