name: 'Clear Disk Space'
description: 'Clear Disk Space'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "clear_disk_space"

    - name: Print Disk Space (pre-clear)
      shell: bash
      run: |
        echo "Available disk space before clearing:"
        df -h

    - name: Clear Disk Space (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "/usr/local/.ghcup"
        sudo rm -rf "/opt/hostedtoolcache/CodeQL"
        sudo rm -rf "/usr/local/julia1.12.1"
        sudo rm -rf "/usr/lib/google-cloud-sdk"

    - name: Clear Disk Space (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        rm -rf "/c/Program Files (x86)/Android"
        rm -rf "/c/Program Files/dotnet"
        rm -rf "/c/ghcup"
        rm -rf "/c/Program Files/MongoDB"
        rm -rf "/c/Program Files/PostgreSQL"
        rm -rf "/c/Program Files/Azure Cosmos DB Emulator"
        rm -rf "/c/Program Files (x86)/Microsoft SDKs/UWPNuGetPackages"
        rm -rf "/c/Windows/assembly/NativeImages_v4.0.30319_64"
        rm -rf "/c/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk"
        
    - name: Print Disk Space (post-clear)
      shell: bash
      run: |
        echo "Available disk space after clearing:"
        df -h

    - uses: Silverlan/common_actions/action_end@main
