name: 'Get GLM'
description: 'Downloads the GLM library'
runs:
  using: "composite"
  steps: 
    - name: Download submodule - GLM 0.9.9.8
      uses: Silverlan/common_actions/curl_download@main
      with:
        download_url: 'https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip'
        file_name: 'glm-0.9.9.8.zip'
  
