name: 'Get GLM'
description: 'Downloads the GLM library'
inputs:
  cmake_definitions:
    description: 'CMake definitions'
    required: true
    default: 'external_libs'
  cmake_var:
    description: 'Name of the CMake variable to set to the include path'
    required: true
    default: ''
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
runs:
  using: "composite"
  steps: 
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      with:
        working-directory: ${{inputs.working-directory}}
      
    - shell: bash
      id: check-exists
      working-directory: ${{inputs.working-directory}}
      run: |
        fileName="./third_party_libs/glm-0.9.9.8.zip"
        if [ -f "$fileName" ]; then
          # It would be better to just skip the following steps,
          # but composite actions don't support if-conditions,
          # so we'll just remove the existing archive and re-execute
          # the steps as a workaround.
          rm "$fileName"
        fi
        
    - name: Download submodule - GLM 0.9.9.8
      uses: Silverlan/common_actions/curl_download@main
      with:
        download_url: 'https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip'
        file_name: 'glm-0.9.9.8.zip'
        working-directory: ${{inputs.working-directory}}
        
    - shell: bash
      id: set-cmake-var
      working-directory: ${{inputs.working-directory}}
      run: |
        newCmakeDef=" -D${{ inputs.cmake_var }}=$PWD/third_party_libs/glm"
        echo ::set-output name=cmakeDefLocal::$(echo $newCmakeDef)

    - name: Define CMake Variable
      uses: Silverlan/common_actions/define_cmake_var@main
      with:
        cmake_var: '${{ steps.set-cmake-var.outputs.cmakeDefLocal }}'
        
