name: 'Curl Download'
description: 'Download archive file via curl and extract'
inputs:
  download_url:
    description: 'Download Url'
    required: true
  file_name:
    description: 'File Name'
    required: true
  download_dir:
    description: 'Download Directory'
    required: true
    default: 'third_party_libs'
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
runs:
  using: "composite"
  steps: 
    - name: Curl Download
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        mkdir -p ${{ inputs.download_dir }}
        cd ${{ inputs.download_dir }}

        curl -LJO ${{ inputs.download_url }}
        7z x ${{ inputs.file_name }} -aos -y
        cd ../
