name: 'Curl Download'
description: 'Download archive file via curl and extract'
inputs:
  download_url:
    description: 'Download Url'
    required: true
  file_name:
    description: 'File Name'
    required: true
  download_dir:
    description: 'Download Directory'
    required: true
    default: 'third_party_libs'
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action Start: curl_download ===\ndownload_url: ${{inputs.download_url}}\nfile_name: ${{inputs.file_name}}\ndownload_dir: ${{inputs.download_dir}}\nworking-directory: ${{inputs.working-directory}}\n"

    - name: Curl Download
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        mkdir -p ${{ inputs.download_dir }}
        cd ${{ inputs.download_dir }}

        curl -LJO ${{ inputs.download_url }}
        7z x ${{ inputs.file_name }} -aos -y
        cd ../

    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action End: curl_download ==="
