name: Rebuild boost
description: 'Download and build boost 1.79.0'
inputs:
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
runs:
  using: "composite"
  steps:
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      with:
        working-directory: ${{inputs.working-directory}}
      
    - name: Build zlib
      uses: Silverlan/common_actions/build_zlib@main
      with:
        working-directory: ${{inputs.working-directory}}

    - name: Download boost
      uses: Silverlan/common_actions/curl_download@main
      with:
        download_url: 'https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.zip'
        file_name: 'boost_1_79_0.zip'
        working-directory: ${{inputs.working-directory}}

    - name: Build boost
      id: build-boost
      working-directory: ${{inputs.working-directory}}
      shell: bash
      run: |
        mv "./third_party_libs/boost_1_79_0" "./third_party_libs/boost" 
        cd "./third_party_libs/boost"
        echo "Running boost bootstrap..."
        if [ "$RUNNER_OS" == "Linux" ]; then
          ./bootstrap.sh
          BOOST_TOOLSET="gcc"
        else
          ./bootstrap.bat
          BOOST_TOOLSET="msvc-14.3"
        fi
        echo "Running b2..."
        ./b2 toolset=$BOOST_TOOLSET address-model=64 stage variant=release link=shared runtime-link=shared -j3
        ./b2 toolset=$BOOST_TOOLSET address-model=64 stage variant=release link=static runtime-link=shared -j3
        ZLIB_SOURCE="$PWD/third_party_libs/zlib"
        ZLIB_INCLUDE="$PWD/third_party_libs/zlib"
        ZLIB_LIBPATH="$PWD/third_party_libs/zlib/build/RelWithDebInfo"
        echo "Running b2 for zlib..."
        ./b2 toolset=$BOOST_TOOLSET address-model=64 stage variant=release link=shared runtime-link=shared --with-iostreams -sZLIB_SOURCE=$ZLIB_SOURCE -sZLIB_INCLUDE=$ZLIB_INCLUDE -sZLIB_LIBPATH=$ZLIB_LIBPATH
        ./b2 toolset=$BOOST_TOOLSET address-model=64 stage variant=release link=static runtime-link=shared --with-iostreams -sZLIB_SOURCE=$ZLIB_SOURCE -sZLIB_INCLUDE=$ZLIB_INCLUDE -sZLIB_LIBPATH=$ZLIB_LIBPATH
        echo "Done!"
        
