name: 'Define CMake Var'
description: 'Defines a global CMake variable'
inputs:
  cmake_var:
    description: 'Name of the CMake variable to set'
    required: true
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action Start: define_cmake_var ===\ncmake_var: ${{inputs.cmake_var}}\n"

    - name: Define CMake Var
      shell: bash
      run: |
        echo "Defining var: ${{ inputs.cmake_var }}"
        printf '%s' " ${{ inputs.cmake_var }}" >> cmake_vars.txt
        value="$(cat cmake_vars.txt)"
        echo "Defined cmake_vars: $value"

    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action End: define_cmake_var ==="
