name: 'Get CMake Vars'
description: 'Gets all global CMake vars'
outputs:
  cmake_vars:
    description: 'Will contain the defined variables'
    value: ${{ steps.get-vars.outputs.cmake_vars }}
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "get_cmake_vars"
        input_values: "cmake_vars: ${{inputs.cmake_vars}}"

    - name: Get Vars
      id: get-vars
      shell: bash
      run: |
        if [[ -f "cmake_vars.txt" ]]; then
          value="$(cat cmake_vars.txt)"
        else
          value=""
        fi
        echo "cmake_vars=$(echo $value)" >> $GITHUB_OUTPUT

    - uses: Silverlan/common_actions/action_end@main
