name: 'Get CMake Vars'
description: 'Gets all global CMake vars'
outputs:
  cmake_vars:
    description: 'Will contain the defined variables'
    value: ${{ steps.get-vars.outputs.cmake_vars }}
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action Start: get_cmake_vars ===\ncmake_vars: ${{inputs.cmake_vars}}\n"

    - name: Get Vars
      id: get-vars
      shell: bash
      run: |
        if [[ -f "cmake_vars.txt" ]]; then
          value="$(cat cmake_vars.txt)"
        else
          value=""
        fi
        echo "::set-output name=cmake_vars::$(echo $value)"

    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action End: get_cmake_vars ==="
