name: 'Get zlib'
description: 'Downloads the zlib library'
inputs:
  cmake_definitions:
    description: 'CMake definitions'
    required: true
    default: 'external_libs'
  cmake_var:
    description: 'Name of the CMake variable to set to the include path'
    required: true
    default: ''
  working-directory:
    description: 'Working Directory'
    required: true
    default: '.'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "build_zlib"
        input_values: "cmake_definitions: ${{inputs.cmake_definitions}},cmake_var: ${{inputs.cmake_var}},working-directory: ${{inputs.working-directory}}"

    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      with:
        working-directory: ${{inputs.working-directory}}
      
    - name: Set zlib library name
      id: zlib-lib
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          zlibLibName=libz
        else
          zlibLibName=zlib
        fi
        echo "lib-name=$zlibLibName" >> $GITHUB_OUTPUT
      
    - name: Build submodule - zlib
      uses: Silverlan/common_actions/build_submodule@main
      with:
        repo: 'https://github.com/madler/zlib.git'
        repo_name: 'zlib'
        repo_branch: 'master'
        build_target: zlib
        lib_name: ${{ matrix.config.build_type }}/${{ steps.zlib-lib.outputs.lib-name }}
        cmake_var: 'ZLIB_INCLUDE_DIR'
        cmake_var_alias: 'DEPENDENCY_ZLIB_INCLUDE'
        cmake_var_lib: 'ZLIB_LIBRARY'
        cmake_var_lib_alias: 'DEPENDENCY_ZLIB_LIBRARY'
        include_dir: '.'
        working-directory: ${{inputs.working-directory}}
    - name: Copy zconf.h
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        cp -n ./build/third_party_libs/zlib/zconf.h ./third_party_libs/zlib/zconf.h
        
    - uses: Silverlan/common_actions/action_end@main
      
