name: 'Upload binaries'
description: 'Upload build binaries.'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "upload_build_binaries"
        input_values: ""

    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      
    - uses: actions/upload-artifact@v4
      with:
        name: build-binaries
        retention-days: 5
        path: |
          ${{ matrix.config.build_dir }}/**/*${{ env.GA_SHARED_LINK_LIBRARY_EXT }}
          ${{ matrix.config.build_dir }}/**/*${{ env.GA_SHARED_BINARY_LIBRARY_EXT }}
          ${{ matrix.config.build_dir }}/**/*${{ env.GA_STATIC_LINK_LIBRARY_EXT }}
          ${{ matrix.config.build_dir }}/**/*.h
          ${{ matrix.config.build_dir }}/**/*.hpp
 
    - uses: Silverlan/common_actions/action_end@main
