name: 'Upload binaries'
description: 'Upload build binaries.'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action Start: upload_build_binaries ===\n"

    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: build-binaries
        retention-days: 5
        path: |
          ${{ matrix.config.build_dir }}/**/*${{ env.GA_SHARED_LINK_LIBRARY_EXT }}
          ${{ matrix.config.build_dir }}/**/*${{ env.GA_SHARED_BINARY_LIBRARY_EXT }}
          ${{ matrix.config.build_dir }}/**/*${{ env.GA_STATIC_LINK_LIBRARY_EXT }}
          ${{ matrix.config.build_dir }}/**/*.h
          ${{ matrix.config.build_dir }}/**/*.hpp
 
    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action End: upload_build_binaries ==="
