name: 'Build geometric tools'
description: 'Downloads and builds the GeometricTools library'
inputs:
  working-directory:
    description: 'Working Directory'
    required: true
    default: '.'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "build_geometric_tools"
        input_values: "working-directory: ${{inputs.working-directory}}"

    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      with:
        working-directory: ${{inputs.working-directory}}
      
    - name: Setup GeometricTools
      id: setup-gt
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "::set-output name=gt_build_target::Mathematics"
        else
          echo "::set-output name=gt_build_target::GTE/GTMathematics.v17"
        fi
        
    - name: Build GeometricTools
      uses: Silverlan/common_actions/build_submodule@main
      with:
        repo: 'https://github.com/davideberly/GeometricTools.git'
        repo_name: 'GeometricTools'
        build_target_windows: '${{ github.workspace }}/third_party_libs/GeometricTools/${{ steps.setup-gt.outputs.gt_build_target }}'
        build_target_linux: 'Mathematics'
        lib_name: 'third_party_libs/GeometricTools/GTE/GTMathematics.v17'
        cmake_var: 'DEPENDENCY_GEOMETRIC_TOOLS_INCLUDE'
        top_level_dir: 'third_party_libs'
        cmake_script_location: 'third_party_libs/GeometricTools/GTE'
        build_type: 'Release'
        include_dir: 'GTE'
        commit_id: 'aa09f9ca5200703557b37d01f7d8018f80035bd9'
        working-directory: ${{inputs.working-directory}}
        # commit_id: '0cbd458d45d3b2766c17746dd018185e7321696e'
      
    - uses: Silverlan/common_actions/action_end@main
