name: 'Setup Clang'
description: 'Install Clang'
inputs:
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
runs:
  using: "composite"
  steps: 
    - name: Install Prerequisites
      shell: bash
      with:
        working-directory: ${{inputs.working-directory}}
      run:   |
        sudo add-apt-repository ppa:savoury1/llvm-defaults-14
        sudo apt update
        sudo apt install clang-14
        sudo apt install libstdc++-12-dev
        sudo apt install libstdc++6
        
    - name: Set Environment Variables
      shell: bash
      with:
        working-directory: ${{inputs.working-directory}}
      run:   |
        echo "CC=/usr/bin/clang-14" >> $GITHUB_ENV
        echo "CXX=/usr/bin/clang++-14" >> $GITHUB_ENV
  
