name: 'Download binaries'
description: 'Download build binaries.'
inputs:
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "download_build_binaries"
        input_values: "working-directory: ${{inputs.working-directory}}"

    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      
    - name: Download binaries
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: pragma-generic-ci.yml
        workflow_conclusion: success
        pr: ${{github.event.pull_request.number}}
        commit: ${{github.event.pull_request.head.sha}}
        branch: actions
        event: push
        name: build-binaries
        path: "./${{ matrix.config.build_dir }}"
        repo: ${{github.repository}}
        check_artifacts:  false
        working-directory: ${{inputs.working-directory}}
      
    - uses: Silverlan/common_actions/action_end@main
