name: 'Build Submodule'
description: 'Downloads and builds a git submodule'
inputs:
  repo:
    description: 'Repository Url'
    required: true
  repo_name:
    description: 'Name of the repository'
    required: true
  repo_branch:
    description: 'Branch to clone'
    required: true
    default: 'master'
  build_target:
    description: 'Main target to build'
    required: true
  build_dir:
    description: 'The directory to write the build files to'
    required: true
    default: 'build'
  build_type:
    description: 'Build Type'
    required: true
    default: ''
  root_dir:
    description: 'The directory in which the submodule should reside in'
    required: true
    default: 'third_party_libs'
  cmake_definitions:
    description: 'CMake definitions'
    required: true
    default: ''
  cmake_var:
    description: 'Name of the CMake variable to set to the include path'
    required: true
    default: ''
  cmake_var_lib:
    description: 'Name of the CMake variable to set to the library path'
    required: true
    default: ''
  cmake_script_location:
    description: 'The location of the CMake script'
    required: true
    default: '.'
  include_dir:
    description: 'Name of the include directory'
    required: true
    default: 'include'
runs:
  using: "composite"
  steps: 
    - name: Clone
      uses: Silverlan/common_actions/get_submodule@actions
      with:
        dir: '${{ inputs.root_dir }}'
        repo: ${{ inputs.repo }}
        repo_name: ${{ inputs.repo_name }}
        repo_branch: ${{ inputs.repo_branch }}
        cmake_definitions: ${{ inputs.cmake_definitions }}
        cmake_var: ${{ inputs.cmake_var }}
        include_dir: ${{ inputs.include_dir }}

    - name: Env
      shell: bash
      run: |
        echo "NEW CMAKE DEFS:"
        echo ${{ env.cmake_definitions }}
        echo "GITHUB_ENV:"
        echo ${{ GITHUB_ENV.cmake_definitions }}
        if [[ "${{ inputs.build_type }}" != "" ]]; then
          echo "GA_BUILD_TYPE=${{ inputs.build_type }}" >> $GITHUB_ENV
        else
          echo "GA_BUILD_TYPE=${{ matrix.config.build_type }}" >> $GITHUB_ENV
        fi

    - name: Build
      uses: Silverlan/common_actions/build_cmake@actions
      with:
        build_type: ${{ env.GA_BUILD_TYPE }}
        build_generator: ${{ matrix.config.generators }}
        build_target: ${{ inputs.build_target }}
        build_dir: '${{ inputs.build_dir }}/${{ inputs.root_dir }}/${{ inputs.repo_name }}'
        cmake_definitions: ${{ env.cmake_definitions }}
        cmake_var: ${{ inputs.cmake_var_lib }}
        cmake_script_location: '${{ inputs.root_dir }}/${{ inputs.repo_name }}/${{ inputs.cmake_script_location }}'
  
