name: 'Setup'
description: 'Basic setup'
inputs:
  cc_version:
    description: 'CC Version'
    required: true
    default: 'gcc-12'
  cxx_version:
    description: 'CXX Version'
    required: true
    default: 'g++-12'
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action Start: setup ===\ncc_version: ${{inputs.cc_version}}\ncxx_version: ${{inputs.cxx_version}}\nworking-directory: ${{inputs.working-directory}}\n"

    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      with:
        working-directory: ${{inputs.working-directory}}
      
    - name: Install GCC
      shell: bash
      id: determine-build-type
      working-directory: ${{inputs.working-directory}}
      run: |
        echo "Runner OS: $RUNNER_OS"
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "Installing ${{ inputs.cxx_version }}..."
          sudo apt update
          sudo apt install ${{ inputs.cc_version }} ${{ inputs.cxx_version }}
        fi
        
    - name: Install Clang
      if: runner.os == 'Linux'
      uses: Silverlan/common_actions/setup_clang@main
      with:
        working-directory: ${{inputs.working-directory}}

    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action End: setup ==="
