name: 'Setup'
description: 'Basic setup'
runs:
  using: "composite"
  steps: 
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@actions
      
    - name: Install GCC-11
      shell: bash
      id: determine-build-type
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt update
          sudo apt install gcc-11 g++-11
        fi
