name: 'Setup'
description: 'Basic setup'
inputs:
  cc_version:
    description: 'CC Version'
    required: true
    default: 'gcc-12'
  cxx_version:
    description: 'CXX Version'
    required: true
    default: 'g++-12'
runs:
  using: "composite"
  steps: 
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      
    - name: Install GCC
      shell: bash
      id: determine-build-type
      run: |
        echo "Runner OS: $RUNNER_OS"
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "Installing ${{ inputs.cxx_version }}..."
          sudo apt update
          sudo apt install ${{ inputs.cc_version }} ${{ inputs.cxx_version }}
        fi
