name: 'Setup'
description: 'Basic setup'
runs:
  using: "composite"
  steps: 
    - name: Install GCC-11
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install gcc-11 g++-11
