name: 'Handle Action Error'
description: 'Handle Action Error'
runs:
  using: "composite"
  steps: 
    - name: Print
      shell: bash
      run: |
        function print_task() {
          output="$1"
          t="$3"
          echo "printf \"\033[0;31m$t> $output\n\"" >> action_print.sh

          echo "printf \"\033[0;31m$t Input Values:\n\"" >> action_print.sh
          IFS=',' read -ra ADDR <<< "$2"
          for i in "${ADDR[@]}"; do
            echo "printf \"\033[1;31m$t - $i\n\"" >> action_print.sh
          done
        }
        
        IFS='#' read -ra ADDR <<< "${{ env.GA_SUB_STEP }}"
        str=""
        first='2'
        curAction=''
        args=''
        for i in "${ADDR[@]}"; do
          IFS='?' read -ra CMP <<< "$i"
          if [ $first -eq '2' ] 
          then
            first='1'
          else
            if [ $first -eq '1' ] 
            then
              first='0'
            else
              str="$str > "
            fi
            str="$str${CMP[0]}"
            curAction=${CMP[0]}
            args=${CMP[1]}
          fi
        done
        
        output="Failure Action: $str"
        echo "printf \"\033[0;31m=== $output ===\n\"" >> action_print.sh
        
        t=''
        first='1'
        for i in "${ADDR[@]}"; do
          if [ $first -eq '1' ]
          then
            first='0'
          else
            IFS='?' read -ra CMP <<< "$i"
            print_task "${CMP[0]}" "${CMP[1]}" "$t"
            t="$t \t"
          fi
        done
        
        # echo "printf \"\033[0;31mInput Values:\n\"" >> action_print.sh
        IFS=',' read -ra ADDR <<< "$args"
        #for i in "${ADDR[@]}"; do
        #  echo "printf \"\033[1;31m$i\n\"" >> action_print.sh
        #done
        
        size=${#output}
        output=""
        size=$size+8
        for (( c=1; c<=$size; c++ ))
        do
           output="$output=";
        done
        echo "printf \"\033[0;31m$output\n\"" >> action_print.sh
        sh action_print.sh
        
    - name: Discord notification
      if: failure()
      env:
        DISCORD_WEBHOOK: 'https://discord.com/api/webhooks/1039183893301035048/Ua8A2yo6CiI6F8UsCEUUbCYBykXezFkdBJJnMr9wXZDIOHO9azeOZPwHR2JU5yhnZjhU'
      uses: Ilshidur/action-discord@master
      with:
        args: 'A workflow has failed!'

    - uses: mxschmitt/action-tmate@v3
      name: CI
