name: Release Nightly Binaries
description: 'Release nightly binaries'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  commit:
    description: 'Commit Hash'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Generate Release Archive
      shell: bash
      id: generate-archive
      run: |
        cd release
        if [ "$RUNNER_OS" == "Linux" ]; then
          archiveName=binaries_linux64.tar.gz
          tar -czvf $archiveName *
        else
          archiveName=binaries_windows64.zip
          tar -cvf $archiveName *
        fi
        mv $archiveName ../$archiveName
        echo "::set-output name=archive-name::$archiveName"
        
    - name: Update Nightly Tag
      uses: rickstaa/action-create-tag@v1
      if: runner.os == 'Linux'
      with:
        tag: "latest"
        force_push_tag: true

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ steps.generate-archive.outputs.archive-name }}"
        body: "Automatically generated binaries."
        commit: ${{ inputs.commit }}
        token: ${{ inputs.token }}
        tag: latest
        replacesArtifacts: true
        allowUpdates: true
