name: Release Nightly Binaries
description: 'Release nightly binaries'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  commit:
    description: 'Commit Hash'
    required: true
    default: ''
  update_tag:
    description: 'Update Tag?'
    required: true
    default: '1'
  working-directory:
    description: 'Working Directory'
    required: true
    default: './release'
runs:
  using: "composite"
  steps:
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "release_nightly_binaries"
        input_values: "token: ${{inputs.token}},commit: ${{inputs.commit}},update_tag: ${{inputs.update_tag}},working-directory: ${{inputs.working-directory}}"

    - name: Generate Release Archive
      shell: bash
      working-directory: ${{inputs.working-directory}}
      id: generate-archive
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          archiveName=binaries_linux64.tar.gz
          tar -czvf $archiveName *
        else
          archiveName=binaries_windows64.zip
          vcpkg install 7zip
          "7z.exe" a $archiveName "*.*" -r
        fi
        mv $archiveName ../$archiveName
        echo "::set-output name=archive-name::$archiveName"
        
    - name: Update Nightly Tag
      uses: rickstaa/action-create-tag@v1.3.9
      continue-on-error: true
      if: runner.os == 'Linux' && ${{ inputs.update_tag == '1' }}
      with:
        tag: "latest"
        force_push_tag: true

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{inputs.working-directory}}/../${{ steps.generate-archive.outputs.archive-name }}"
        body: "Automatically generated binaries."
        commit: ${{ inputs.commit }}
        token: ${{ inputs.token }}
        tag: latest
        replacesArtifacts: true
        allowUpdates: true

    - uses: Silverlan/common_actions/action_end@main
