name: 'Generic CMake build'
description: 'Builds the specified project'
inputs:
  build_action:
    description: 'Build action'
    required: true
  working-directory:
    description: 'Working Directory'
    required: true
    default: './'
runs:
  using: "composite"
  steps: 
    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action Start: generic_build_workflow ===\nbuild_action: ${{inputs.build_action}}\nworking-directory: ${{inputs.working-directory}}\n"

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup
      id: setup
      uses: Silverlan/common_actions/setup@main
      with:
        working-directory: ${{inputs.working-directory}}

    - name: Download binaries
      uses: Silverlan/common_actions/download_build_binaries@main
      continue-on-error: true
      with:
        working-directory: ${{inputs.working-directory}}

    - name: Build
      id: build
      uses: ${{ inputs.build_action }}
      with:
        working-directory: ${{inputs.working-directory}}

    - name: Upload binaries
      uses: Silverlan/common_actions/upload_build_binaries@main
      with:
        working-directory: ${{inputs.working-directory}}
       
    - uses: Silverlan/common_actions/print_msg@main
      with:
        message: "=== Action End: generic_build_workflow ==="
