name: 'Action End'
description: 'Action End'
runs:
  using: "composite"
  steps: 
    - name: Print
      shell: bash
      run: |
        IFS='#' read -ra ADDR <<< "${{ env.GA_SUB_STEP }}"
        str=""
        first='2'
        curAction=''
        args=''
        for i in "${ADDR[@]}"; do
          IFS='?' read -ra CMP <<< "$i"
          if [ $first -eq '2' ] 
          then
            first='1'
          else
            if [ $first -eq '1' ] 
            then
              first='0'
            else
              str="$str > "
            fi
            str="$str${CMP[0]}"
            curAction=${CMP[0]}
            args=${CMP[1]}
          fi
        done
        
        output="Action End: $str"
        printf "\033[0;35m=== $output ===\n"
        
        # Remove from env variables
        text="${{ env.GA_SUB_STEP }}"
        envVars=$(echo $text | sed 's![^#]*$!!')
        envVars=${envVars%?}
        
        echo "GA_SUB_STEP=$(echo $envVars)" >> $GITHUB_ENV
        
